name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
        
    - name: Run tests
      run: |
        pytest --cov=. --cov-report=xml
        
    - name: LangSmith Integration Check
      env:
        LANGCHAIN_TRACING_V2: true
        LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_API_KEY }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: |
        python -c "
        from config import Config
        from monitoring import get_monitor
        print('✅ LangSmith configuration validated')
        monitor = get_monitor()
        health = monitor.get_system_health()
        print(f'✅ System health: {health[\"system_status\"]}')
        "

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: ./
        
    - name: Post-Deployment Health Check
      run: |
        sleep 30  # Wait for deployment to stabilize
        curl -f ${{ secrets.VERCEL_DEPLOYMENT_URL }}/health || exit 1
        
    - name: Notify LangSmith of Deployment
      env:
        LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_API_KEY }}
      run: |
        python -c "
        import os
        from datetime import datetime
        print(f'🚀 Deployment completed at {datetime.now()}')
        print('📊 LangSmith monitoring active')
        "